[package]
name = "aoc2"
version = "0.1.0"
authors = ["Isaac Diamond <isaacd9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"

[[bin]]
name = "aoc2"
path = "main.rs"
